name: lbry-cli
title: LBRY CLI
type: app
base: core24
confinement: strict
version: master
summary: LBRY Command Line Interface
description: The LBRY Command Line Interface (CLI) to interact with the LBRY Daemon.
license: MIT
website: https://lbry.org
source-code: https://github.com/LBRYFoundation/lbry-cli
issues:
  - https://github.com/LBRYFoundation/lbry-cli/issues
contact: board@lbry.org
donation:
  - https://lbry.org/#donation

apps:
  lbry-cli:
    command: bin/lbry-cli
    plugs:
      - network

parts:
  lbry-cli:
    plugin: go
    source: .
    build-snaps: [go]
    override-build: go build -o ${CRAFT_PART_INSTALL}/bin/lbry-cli

platforms:
  dinges:
    build-on: amd64
    build-for: [amd64, armhf]
