name: lbry-cli
base: core24
confinement: classic
version: master
summary: The LBRY Command Line Interface (CLI) to interact with the LBRY Daemon.
description: The LBRY Command Line Interface (CLI) to interact with the LBRY Daemon.
