name: lbry-cli
title: LBRY CLI
type: app
base: core24
confinement: strict
version: master
summary: LBRY Command Line Interface
description: The LBRY Command Line Interface (CLI) to interact with the LBRY Daemon.
license: MIT
website: https://lbry.org
source-code: https://github.com/LBRYFoundation/lbry-cli
issues:
  - https://github.com/LBRYFoundation/lbry-cli/issues
contact: board@lbry.org
donation:
  - https://lbry.org/#donation

platforms:
  amd64:
  arm64:
  armhf:
  i386:
  ppc64el:
  riscv64:
  s390x:

plugs:
  network:

parts:
  lbry-cli:
    plugin: go
    source: .
