name: Snapcraft Edge

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic
      - name: Install Go
        run: sudo snap install go --classic
      - name: Build and pack Snap package
        run: snapcraft pack
      - name: Upload Snap package
        run: snapcraft upload --release=edge *.snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
