name: Snapcraft Edge

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armhf, i386, powerpc, ppc64el, riscv64, s390x]
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
        id: build
        with:
          snapcraft-args: --target-arch=${{ matrix.arch }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
